addSbtPlugin("org.scalariform"   % "sbt-scalariform"      % "1.6.0")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph" % "0.8.2")
addSbtPlugin("com.dwijnand"      % "sbt-dynver"           % "1.1.1")
addSbtPlugin("com.typesafe.sbt"  % "sbt-twirl"            % "1.3.2")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"          % "0.1.10")
