addSbtPlugin("org.scalariform"   % "sbt-scalariform"      % "1.8.2")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph" % "0.9.0")
addSbtPlugin("com.dwijnand"      % "sbt-dynver"           % "2.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-twirl"            % "1.3.13")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"          % "0.3.3")
